# Generated by Django 5.2.3 on 2025-06-19 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCommentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workspace.taskcomment')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comment_files', to='storage.workspacefile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comment_files', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_files', to='workspace.task')),
            ],
            options={
                'indexes': [models.Index(fields=['comment'], name='workspace_t_comment_b3a91b_idx'), models.Index(fields=['file'], name='workspace_t_file_id_f09cfd_idx'), models.Index(fields=['task'], name='workspace_t_task_id_465124_idx')],
            },
        ),
    ]
