# Generated by Django 5.2.3 on 2025-06-29 11:58

import portal.utils.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_taskcommentfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='schedule',
            field=models.CharField(default='0 0 * * 1', max_length=100, validators=[portal.utils.validators.validate_cron_expression]),
        ),
        migrations.AddField(
            model_name='choreassigned',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chore_assignments', to='workspace.workspace'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='choreassigned',
            index=models.Index(fields=['workspace'], name='workspace_c_workspa_0d042e_idx'),
        ),
    ]
