# Generated by Django 5.2.3 on 2025-07-27 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fields', models.JSONField()),
                ('category_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form.form')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('steps', models.JSONField()),
                ('category_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('stage_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_instances', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='form.process')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_instances', to='workspace.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['workspace'], name='form_form_workspa_712520_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['workspace', 'category_key'], name='form_form_workspa_169551_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['workspace'], name='form_formsu_workspa_39c44b_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['workspace', 'form'], name='form_formsu_workspa_707387_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['workspace'], name='form_proces_workspa_200364_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['workspace', 'category_key'], name='form_proces_workspa_558a56_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['workspace'], name='form_proces_workspa_fc4576_idx'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['workspace', 'process'], name='form_proces_workspa_43b724_idx'),
        ),
    ]
